### PR TITLE
Feature/matrix

### PR DESCRIPTION
**Pull request by relumesaros**

### CODE REVIEW

**Review by evaneus — COMMENTED** [review]
Quick comment - think you may need to add types/schema docs using pie-models?

**Comment by relumesaros** [comment]
> Quick comment - think you may need to add types/schema docs using pie-models?

Hi @evaneus 
I've added the types/schema docs using pie-models

**Comment by edeustace** [comment]
looks good - can you add some tests?

**Comment by relumesaros** [comment]
> looks good - can you add some tests?

Added

**Pull request merged**
